---

- name: Generate banner configurations
  template:
    src: "banner.j2"
    dest: "/home/ubuntu/vagrant_data/ansible/roles/core/configs/{{ inventory_hostname }}/banner.cfg"
  tags:
    - banner