---
# vars file for asa-vpn
ras_cfg: deploy
yml_dir: group_vars/ras
role_root: ansible/roles

date: "{{ now().strftime('%Y_%m_%d') | string }}"
time: "{{ now().strftime('%H-%M-%S') | string }}"


#, multiline=False, ignorecase=True)
# | regex_search('^\\d+:\\d+:\\d+', multiline=False, ignorecase=True)

backup_dir: "/gitnet/ras-processed/changes/dst_sync/{{ inventory_hostname }}"
changes_dir: "{{ backup_dir }}/{{ date }}"
pre_conf_file: "{{ changes_dir }}/dst_sync_pre_change.conf"
post_conf_file: "{{ changes_dir }}/dst_sync_post_change.conf"
config_dir: "{{ backup_dir }}/{{ date }}"
config_file_gp: "{{ changes_dir }}/dst_gp_sync.conf"
config_file_dst: "{{ changes_dir }}/dst_sync.conf"
ld6_sync_group: "{{ ansible_limit }}-sync-ld6"
ma3_sync_group: "{{ ansible_limit }}-sync-ma3"
