Port-channel1.384: {admin-state: up, interface: Port-channel1.384, ip-add: 10.180.161.196,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.708: {admin-state: ' shutdown', interface: Port-channel1.708, ip-add: 10.181.1.1,
  nameif: gib-cde-deployment-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.709: {admin-state: up, interface: Port-channel1.709, ip-add: 10.181.2.1,
  nameif: gib-cde-web1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.710: {admin-state: up, interface: Port-channel1.710, ip-add: 10.181.3.1,
  nameif: gib-cde-app1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.711: {admin-state: up, interface: Port-channel1.711, ip-add: 10.181.4.1,
  nameif: gib-cde-int-pres-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.712: {admin-state: up, interface: Port-channel1.712, ip-add: 10.181.5.1,
  nameif: gib-cde-api-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.713: {admin-state: up, interface: Port-channel1.713, ip-add: 10.181.6.1,
  nameif: gib-cde-ext-pres-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.714: {admin-state: up, interface: Port-channel1.714, ip-add: 10.181.7.1,
  nameif: gib-cde-ext-api, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.715: {admin-state: up, interface: Port-channel1.715, ip-add: 10.181.8.1,
  nameif: gib-cde-lan02, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.716: {admin-state: up, interface: Port-channel1.716, ip-add: 10.181.9.1,
  nameif: gib-cde-lan03, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.717: {admin-state: up, interface: Port-channel1.717, ip-add: 10.181.10.1,
  nameif: gib-cde-mgmt-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.718: {admin-state: up, interface: Port-channel1.718, ip-add: 10.181.11.1,
  nameif: gib-cde-lan04, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.719: {admin-state: up, interface: Port-channel1.719, ip-add: 10.181.12.1,
  nameif: gib-cde-lan05, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.720: {admin-state: up, interface: Port-channel1.720, ip-add: 10.181.13.1,
  nameif: gib-cde-lan06, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.721: {admin-state: up, interface: Port-channel1.721, ip-add: 10.181.14.1,
  nameif: gib-cde-lan07, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.722: {admin-state: up, interface: Port-channel1.722, ip-add: 10.181.15.1,
  nameif: gib-cde-lan08, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.723: {admin-state: up, interface: Port-channel1.723, ip-add: 10.181.16.1,
  nameif: gib-cde-lan09, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.724: {admin-state: up, interface: Port-channel1.724, ip-add: 10.181.17.1,
  nameif: gib-cde-lan10, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.725: {admin-state: up, interface: Port-channel1.725, ip-add: 10.181.18.1,
  nameif: gib-cde-lan11, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.726: {admin-state: up, interface: Port-channel1.726, ip-add: 10.181.19.1,
  nameif: gib-cde-lan12, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.727: {admin-state: up, interface: Port-channel1.727, ip-add: 10.181.20.1,
  nameif: gib-cde-lan13, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.728: {admin-state: up, interface: Port-channel1.728, ip-add: 10.181.21.1,
  nameif: gib-cde-lan14, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.729: {admin-state: up, interface: Port-channel1.729, ip-add: 10.181.22.1,
  nameif: gib-cde-lan15, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.730: {admin-state: up, interface: Port-channel1.730, ip-add: 10.181.23.1,
  nameif: gib-cde-lan16, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.758: {admin-state: up, interface: Port-channel1.758, ip-add: 10.181.65.1,
  nameif: gib-noncde-deployment-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.759: {admin-state: up, interface: Port-channel1.759, ip-add: 10.181.66.1,
  nameif: gib-noncde-web1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.760: {admin-state: up, interface: Port-channel1.760, ip-add: 10.181.67.1,
  nameif: gib-noncde-app1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.761: {admin-state: up, interface: Port-channel1.761, ip-add: 10.181.68.1,
  nameif: gib-noncde-lan01, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.762: {admin-state: up, interface: Port-channel1.762, ip-add: 10.181.69.1,
  nameif: gib-noncde-lan02, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.763: {admin-state: up, interface: Port-channel1.763, ip-add: 10.181.70.1,
  nameif: gib-noncde-lan03, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.764: {admin-state: up, interface: Port-channel1.764, ip-add: 10.181.71.1,
  nameif: gib-noncde-lan04, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.765: {admin-state: up, interface: Port-channel1.765, ip-add: 10.181.72.1,
  nameif: gib-noncde-lan05, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.766: {admin-state: up, interface: Port-channel1.766, ip-add: 10.181.73.1,
  nameif: gib-noncde-lan06, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.767: {admin-state: up, interface: Port-channel1.767, ip-add: 10.181.74.1,
  nameif: gib-noncde-lan07, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.768: {admin-state: up, interface: Port-channel1.768, ip-add: 10.181.75.1,
  nameif: gib-noncde-lan08, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.769: {admin-state: up, interface: Port-channel1.769, ip-add: 10.181.76.1,
  nameif: gib-noncde-lan09, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.770: {admin-state: up, interface: Port-channel1.770, ip-add: 10.181.77.1,
  nameif: gib-noncde-lan10, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.771: {admin-state: up, interface: Port-channel1.771, ip-add: 10.181.78.1,
  nameif: gib-noncde-app2-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.772: {admin-state: up, interface: Port-channel1.772, ip-add: 10.181.79.1,
  nameif: gib-noncde-app3-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.773: {admin-state: up, interface: Port-channel1.773, ip-add: 10.181.80.1,
  nameif: gib-noncde-app4-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.774: {admin-state: up, interface: Port-channel1.774, ip-add: 10.181.81.1,
  nameif: gib-noncde-app5-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.775: {admin-state: up, interface: Port-channel1.775, ip-add: 10.181.82.1,
  nameif: gib-noncde-app6-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.776: {admin-state: up, interface: Port-channel1.776, ip-add: 10.181.83.1,
  nameif: gib-noncde-app7-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.777: {admin-state: up, interface: Port-channel1.777, ip-add: 10.181.84.1,
  nameif: gib-noncde-app8-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.778: {admin-state: up, interface: Port-channel1.778, ip-add: 10.181.85.1,
  nameif: gib-noncde-app9-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.779: {admin-state: up, interface: Port-channel1.779, ip-add: 10.181.86.1,
  nameif: gib-noncde-app10-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.780: {admin-state: up, interface: Port-channel1.780, ip-add: 10.181.87.1,
  nameif: gib-noncde-app11-lan, netmask: 255.255.255.0, security-level: '100'}
