Port-channel1.300: {admin-state: up, interface: Port-channel1.300, ip-add: 10.180.128.2,
  nameif: management, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.302: {admin-state: up, interface: Port-channel1.302, ip-add: 10.180.130.1,
  nameif: server-ilo, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.303: {admin-state: up, interface: Port-channel1.303, ip-add: 10.180.131.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.304: {admin-state: up, interface: Port-channel1.304, ip-add: 10.180.132.1,
  nameif: applications-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.305: {admin-state: up, interface: Port-channel1.305, ip-add: 10.180.133.1,
  nameif: database-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.306: {admin-state: up, interface: Port-channel1.306, ip-add: 10.180.134.1,
  nameif: citrix, netmask: 255.255.255.128, security-level: '100'}
Port-channel1.307: {admin-state: up, interface: Port-channel1.307, ip-add: 10.180.134.129,
  nameif: firewall-ilo, netmask: 255.255.255.128, security-level: '100'}
Port-channel1.309: {admin-state: up, interface: Port-channel1.309, ip-add: 10.180.136.1,
  nameif: proxy-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.310: {admin-state: up, interface: Port-channel1.310, ip-add: 10.180.137.1,
  nameif: backoffice-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.311: {admin-state: up, interface: Port-channel1.311, ip-add: 10.180.138.1,
  nameif: vmware-esx, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.314: {admin-state: up, interface: Port-channel1.314, ip-add: 10.180.139.65,
  nameif: silvertail-poc-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.316: {admin-state: up, interface: Port-channel1.316, ip-add: 10.180.139.129,
  nameif: hdr-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.318: {admin-state: up, interface: Port-channel1.318, ip-add: 10.180.139.193,
  nameif: proofpoint-manager, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.319: {admin-state: up, interface: Port-channel1.319, ip-add: 10.180.139.225,
  nameif: san-mgmt2, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.320: {admin-state: up, interface: Port-channel1.320, ip-add: 10.180.140.1,
  nameif: Stingray-Mgt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.321: {admin-state: up, interface: Port-channel1.321, ip-add: 10.180.141.1,
  nameif: cde-jumphosts, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.323: {admin-state: up, interface: Port-channel1.323, ip-add: 10.180.80.1,
  nameif: server-ilo-10.180.80.0slash24, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.329: {admin-state: up, interface: Port-channel1.329, ip-add: 10.180.142.161,
  nameif: emc-monitoring-dmz, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.330: {admin-state: ' shutdown', interface: Port-channel1.330, ip-add: 10.180.142.193,
  nameif: gib-cde-jumphost, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.331: {admin-state: up, interface: Port-channel1.331, ip-add: 10.180.142.225,
  nameif: scanning-dmz, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.334: {admin-state: up, interface: Port-channel1.334, ip-add: 10.180.143.65,
  nameif: sftp-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.337: {admin-state: up, interface: Port-channel1.337, ip-add: 10.180.143.161,
  nameif: san-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.375: {admin-state: up, interface: Port-channel1.375, ip-add: 10.180.160.162,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
