Port-channel1.130: {admin-state: up, interface: Port-channel1.130, ip-add: 10.180.40.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.131: {admin-state: up, interface: Port-channel1.131, ip-add: 10.180.41.1,
  nameif: proxy-tier-new, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.132: {admin-state: up, interface: Port-channel1.132, ip-add: 10.180.42.1,
  nameif: backoffice-tier-new, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.150: {admin-state: ' shutdown', interface: Port-channel1.150, ip-add: 10.180.48.1,
  nameif: proxy-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.151: {admin-state: ' shutdown', interface: Port-channel1.151, ip-add: 10.180.48.33,
  nameif: backoffice-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.152: {admin-state: ' shutdown', interface: Port-channel1.152, ip-add: 10.180.48.65,
  nameif: authpro-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.153: {admin-state: up, interface: Port-channel1.153, ip-add: 10.180.48.97,
  nameif: sftp-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.154: {admin-state: up, interface: Port-channel1.154, ip-add: 10.180.48.129,
  nameif: hdr-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.155: {admin-state: up, interface: Port-channel1.155, ip-add: 10.180.48.161,
  nameif: crypto-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.160: {admin-state: up, interface: Port-channel1.160, ip-add: 10.180.50.1,
  nameif: application-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.161: {admin-state: up, interface: Port-channel1.161, ip-add: 10.180.51.1,
  nameif: authpro, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.162: {admin-state: up, interface: Port-channel1.162, ip-add: 10.180.52.1,
  nameif: database-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.373: {admin-state: up, interface: Port-channel1.373, ip-add: 10.180.160.98,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
