Port-channel1.340: {admin-state: up, interface: Port-channel1.340, ip-add: 10.180.144.1,
  nameif: server-ilo, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.341: {admin-state: up, interface: Port-channel1.341, ip-add: 10.180.145.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.342: {admin-state: up, interface: Port-channel1.342, ip-add: 10.180.146.1,
  nameif: applications-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.343: {admin-state: up, interface: Port-channel1.343, ip-add: 10.180.147.1,
  nameif: rng-arcade, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.344: {admin-state: up, interface: Port-channel1.344, ip-add: 10.180.148.1,
  nameif: backoffice-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.347: {admin-state: up, interface: Port-channel1.347, ip-add: 10.180.151.1,
  nameif: noncde-jumphosts, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.360: {admin-state: ' shutdown', interface: Port-channel1.360, ip-add: 10.180.157.225,
  nameif: gib-noncde-jumphost, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.361: {admin-state: up, interface: Port-channel1.361, ip-add: 10.180.158.1,
  nameif: caerus-apps-man-2, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.362: {admin-state: up, interface: Port-channel1.362, ip-add: 10.180.159.1,
  nameif: edge-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.364: {admin-state: up, interface: Port-channel1.364, ip-add: 10.180.159.65,
  nameif: webscreen-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.366: {admin-state: up, interface: Port-channel1.366, ip-add: 10.180.159.129,
  nameif: rng-retail, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.367: {admin-state: up, interface: Port-channel1.367, ip-add: 10.180.159.161,
  nameif: f1x2-web, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.368: {admin-state: up, interface: Port-channel1.368, ip-add: 10.180.159.193,
  nameif: f1x2-app, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.369: {admin-state: up, interface: Port-channel1.369, ip-add: 10.180.159.225,
  nameif: caerus-apps-man, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.376: {admin-state: up, interface: Port-channel1.376, ip-add: 10.180.160.194,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
