Port-channel1.378: {admin-state: up, interface: Port-channel1.378, ip-add: 10.180.160.228,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.440: {admin-state: ' shutdown', interface: Port-channel1.440, ip-add: 10.180.168.1,
  nameif: internal-web, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.449: {admin-state: up, interface: Port-channel1.449, ip-add: 10.180.169.129,
  nameif: internal-web-new, netmask: 255.255.255.128, security-level: '100'}
