Port-channel1.100: {admin-state: up, interface: Port-channel1.100, ip-add: 10.120.32.1,
  nameif: cde-web, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.101: {admin-state: up, interface: Port-channel1.101, ip-add: 10.120.32.33,
  nameif: cde-backoffice, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.102: {admin-state: up, interface: Port-channel1.102, ip-add: 10.120.32.65,
  nameif: cde-app, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.115: {admin-state: up, interface: Port-channel1.115, ip-add: 10.120.33.161,
  nameif: mailhosts, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.123: {admin-state: up, interface: Port-channel1.123, ip-add: 10.120.39.1,
  nameif: citrix, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.134: {admin-state: up, interface: Port-channel1.134, ip-add: 10.120.44.1,
  nameif: int-lb, netmask: 255.255.254.0, security-level: '100'}
Port-channel1.140: {admin-state: up, interface: Port-channel1.140, ip-add: 10.120.46.1,
  nameif: storage_data, netmask: 255.255.255.128, security-level: '100'}
Port-channel1.154: {admin-state: up, interface: Port-channel1.154, ip-add: 10.120.48.97,
  nameif: hdr-db, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.162: {admin-state: up, interface: Port-channel1.162, ip-add: 10.120.52.1,
  nameif: database, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.371: {admin-state: up, interface: Port-channel1.371, ip-add: 10.120.160.36,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
