Port-channel1.300: {admin-state: up, interface: Port-channel1.300, ip-add: 10.120.128.4,
  nameif: management, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.302: {admin-state: up, interface: Port-channel1.302, ip-add: 10.120.130.1,
  nameif: server-ilo, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.303: {admin-state: up, interface: Port-channel1.303, ip-add: 10.120.131.1,
  nameif: web-mgt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.304: {admin-state: up, interface: Port-channel1.304, ip-add: 10.120.132.1,
  nameif: app-mgt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.305: {admin-state: up, interface: Port-channel1.305, ip-add: 10.120.133.1,
  nameif: db-mgt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.306: {admin-state: up, interface: Port-channel1.306, ip-add: 10.120.134.1,
  nameif: vmhost-mgt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.307: {admin-state: up, interface: Port-channel1.307, ip-add: 10.120.135.1,
  nameif: firewall-ilo, netmask: 255.255.255.128, security-level: '100'}
Port-channel1.309: {admin-state: up, interface: Port-channel1.309, ip-add: 10.120.136.1,
  nameif: bladelogic-dmz, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.310: {admin-state: up, interface: Port-channel1.310, ip-add: 10.120.137.1,
  nameif: cde-backoffice-mgt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.319: {admin-state: up, interface: Port-channel1.319, ip-add: 10.120.139.225,
  nameif: san-mgmt2, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.320: {admin-state: up, interface: Port-channel1.320, ip-add: 10.120.140.1,
  nameif: Stingray-Mgt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.321: {admin-state: up, interface: Port-channel1.321, ip-add: 10.120.141.1,
  nameif: sc1-cde-jumphost-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.323: {admin-state: up, interface: Port-channel1.323, ip-add: 10.120.80.1,
  nameif: server-ilo2, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.329: {admin-state: up, interface: Port-channel1.329, ip-add: 10.120.142.161,
  nameif: emc-monitoring-dmz, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.333: {admin-state: up, interface: Port-channel1.333, ip-add: 10.120.143.33,
  nameif: sftp-mgt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.334: {admin-state: up, interface: Port-channel1.334, ip-add: 10.120.143.65,
  nameif: scanning-dmz, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.335: {admin-state: up, interface: Port-channel1.335, ip-add: 10.120.143.97,
  nameif: hdr-db-mgt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.336: {admin-state: up, interface: Port-channel1.336, ip-add: 10.120.143.129,
  nameif: Universe_Database_Server, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.337: {admin-state: up, interface: Port-channel1.337, ip-add: 10.120.143.161,
  nameif: san-mgt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.375: {admin-state: up, interface: Port-channel1.375, ip-add: 10.120.160.164,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
