Port-channel1.383: {admin-state: up, interface: Port-channel1.383, ip-add: 10.120.161.164,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.398: {admin-state: up, interface: Port-channel1.398, ip-add: 10.120.162.1,
  nameif: almbuild-int, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.399: {admin-state: up, interface: Port-channel1.399, ip-add: 10.120.163.1,
  nameif: monitoring-int, netmask: 255.255.255.0, security-level: '100'}
