Port-channel1.403: {admin-state: up, interface: Port-channel1.403, ip-add: 10.120.164.100,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.808: {admin-state: up, interface: Port-channel1.808, ip-add: 10.122.1.1,
  nameif: inv-cde-deployment-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.809: {admin-state: up, interface: Port-channel1.809, ip-add: 10.122.2.1,
  nameif: inv-cde-web1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.810: {admin-state: up, interface: Port-channel1.810, ip-add: 10.122.3.1,
  nameif: inv-cde-app1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.811: {admin-state: up, interface: Port-channel1.811, ip-add: 10.122.4.1,
  nameif: inv-cde-int-pres-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.812: {admin-state: up, interface: Port-channel1.812, ip-add: 10.122.5.1,
  nameif: inv-cde-api-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.813: {admin-state: up, interface: Port-channel1.813, ip-add: 10.122.6.1,
  nameif: inv-cde-ext-pres-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.814: {admin-state: up, interface: Port-channel1.814, ip-add: 10.122.7.1,
  nameif: inv-cde-lan01, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.815: {admin-state: up, interface: Port-channel1.815, ip-add: 10.122.8.1,
  nameif: inv-cde-lan02, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.816: {admin-state: up, interface: Port-channel1.816, ip-add: 10.122.9.1,
  nameif: inv-cde-lan03, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.817: {admin-state: up, interface: Port-channel1.817, ip-add: 10.122.10.1,
  nameif: inv-cde-mgmt-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.818: {admin-state: up, interface: Port-channel1.818, ip-add: 10.122.11.1,
  nameif: inv-cde-lan04, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.819: {admin-state: up, interface: Port-channel1.819, ip-add: 10.122.12.1,
  nameif: inv-cde-lan05, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.820: {admin-state: up, interface: Port-channel1.820, ip-add: 10.122.13.1,
  nameif: inv-cde-lan06, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.821: {admin-state: up, interface: Port-channel1.821, ip-add: 10.122.14.1,
  nameif: inv-cde-lan07, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.822: {admin-state: up, interface: Port-channel1.822, ip-add: 10.122.15.1,
  nameif: inv-cde-lan08, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.858: {admin-state: up, interface: Port-channel1.858, ip-add: 10.122.65.1,
  nameif: inv-noncde-deployment-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.859: {admin-state: up, interface: Port-channel1.859, ip-add: 10.122.66.1,
  nameif: inv-noncde-web1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.860: {admin-state: up, interface: Port-channel1.860, ip-add: 10.122.67.1,
  nameif: inv-noncde-app1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.861: {admin-state: up, interface: Port-channel1.861, ip-add: 10.122.68.1,
  nameif: inv-noncde-lan01, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.862: {admin-state: up, interface: Port-channel1.862, ip-add: 10.122.69.1,
  nameif: inv-noncde-lan02, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.863: {admin-state: up, interface: Port-channel1.863, ip-add: 10.122.70.1,
  nameif: inv-noncde-lan03, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.864: {admin-state: up, interface: Port-channel1.864, ip-add: 10.122.71.1,
  nameif: inv-noncde-ext-api, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.865: {admin-state: up, interface: Port-channel1.865, ip-add: 10.122.72.1,
  nameif: inv-noncde-lan05, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.866: {admin-state: up, interface: Port-channel1.866, ip-add: 10.122.73.1,
  nameif: inv-noncde-lan06, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.867: {admin-state: up, interface: Port-channel1.867, ip-add: 10.122.74.1,
  nameif: inv-noncde-lan07, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.868: {admin-state: up, interface: Port-channel1.868, ip-add: 10.122.75.1,
  nameif: inv-noncde-lan08, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.869: {admin-state: up, interface: Port-channel1.869, ip-add: 10.122.76.1,
  nameif: inv-noncde-lan09, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.870: {admin-state: up, interface: Port-channel1.870, ip-add: 10.122.77.1,
  nameif: inv-noncde-lan10, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.871: {admin-state: up, interface: Port-channel1.871, ip-add: 10.122.78.1,
  nameif: inv-noncde-app2-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.872: {admin-state: up, interface: Port-channel1.872, ip-add: 10.122.79.1,
  nameif: inv-noncde-app3-lan, netmask: 255.255.255.0, security-level: '100'}
