Port-channel1.340: {admin-state: up, interface: Port-channel1.340, ip-add: 10.120.144.1,
  nameif: server-ilo, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.341: {admin-state: up, interface: Port-channel1.341, ip-add: 10.120.145.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.342: {admin-state: up, interface: Port-channel1.342, ip-add: 10.120.146.1,
  nameif: app-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.343: {admin-state: up, interface: Port-channel1.343, ip-add: 10.120.147.1,
  nameif: app2-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.344: {admin-state: up, interface: Port-channel1.344, ip-add: 10.120.148.1,
  nameif: backoffice-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.345: {admin-state: up, interface: Port-channel1.345, ip-add: 10.120.149.1,
  nameif: ods-mgmt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.347: {admin-state: up, interface: Port-channel1.347, ip-add: 10.120.151.1,
  nameif: sc1-noncde-jumphost-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.348: {admin-state: up, interface: Port-channel1.348, ip-add: 10.120.152.1,
  nameif: noncde-cf-web-mgmt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.349: {admin-state: up, interface: Port-channel1.349, ip-add: 10.120.153.1,
  nameif: noncde-cf-app-mgmt, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.353: {admin-state: up, interface: Port-channel1.353, ip-add: 10.120.157.1,
  nameif: webcache-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.362: {admin-state: up, interface: Port-channel1.362, ip-add: 10.120.159.1,
  nameif: edge-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.364: {admin-state: up, interface: Port-channel1.364, ip-add: 10.120.159.65,
  nameif: webscreen-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.365: {admin-state: up, interface: Port-channel1.365, ip-add: 10.120.159.97,
  nameif: vc-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.368: {admin-state: up, interface: Port-channel1.368, ip-add: 10.120.159.193,
  nameif: email-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.376: {admin-state: up, interface: Port-channel1.376, ip-add: 10.120.160.196,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
