Port-channel1.200: {admin-state: up, interface: Port-channel1.200, ip-add: 10.120.64.1,
  nameif: noncde-web, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.201: {admin-state: up, interface: Port-channel1.201, ip-add: 10.120.64.33,
  nameif: noncde-backoffice, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.202: {admin-state: up, interface: Port-channel1.202, ip-add: 10.120.64.65,
  nameif: noncde-app, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.203: {admin-state: up, interface: Port-channel1.203, ip-add: 10.120.64.97,
  nameif: cobain, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.204: {admin-state: up, interface: Port-channel1.204, ip-add: 10.120.64.129,
  nameif: noncde-finance-prod, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.205: {admin-state: up, interface: Port-channel1.205, ip-add: 10.120.64.161,
  nameif: noncde-finance-test, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.207: {admin-state: up, interface: Port-channel1.207, ip-add: 10.120.64.225,
  nameif: non-cde-app2, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.213: {admin-state: up, interface: Port-channel1.213, ip-add: 10.120.69.1,
  nameif: noncde-webcache, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.214: {admin-state: up, interface: Port-channel1.214, ip-add: 10.120.69.33,
  nameif: BACS, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.216: {admin-state: up, interface: Port-channel1.216, ip-add: 10.120.69.99,
  nameif: cobain-iptv, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.218: {admin-state: up, interface: Port-channel1.218, ip-add: 10.120.69.225,
  nameif: noncde-sccm, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.219: {admin-state: up, interface: Port-channel1.219, ip-add: 10.120.69.193,
  nameif: citrix_netscaler, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.222: {admin-state: up, interface: Port-channel1.222, ip-add: 10.120.72.1,
  nameif: noncde-cf-web, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.223: {admin-state: up, interface: Port-channel1.223, ip-add: 10.120.70.1,
  nameif: vmware-esc, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.231: {admin-state: up, interface: Port-channel1.231, ip-add: 10.120.74.1,
  nameif: int-lb, netmask: 255.255.254.0, security-level: '100'}
Port-channel1.232: {admin-state: up, interface: Port-channel1.232, ip-add: 10.120.65.65,
  nameif: property-prod, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.233: {admin-state: up, interface: Port-channel1.233, ip-add: 10.120.76.1,
  nameif: corporate-web, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.234: {admin-state: up, interface: Port-channel1.234, ip-add: 10.120.65.97,
  nameif: hr-sap, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.262: {admin-state: up, interface: Port-channel1.262, ip-add: 10.120.100.1,
  nameif: noncde-ods, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.263: {admin-state: up, interface: Port-channel1.263, ip-add: 10.120.101.1,
  nameif: trading-dmz, netmask: 255.255.255.224, security-level: '100'}
Port-channel1.264: {admin-state: up, interface: Port-channel1.264, ip-add: 10.120.102.1,
  nameif: noncde-cf-app, netmask: 255.255.255.0, security-level: '100'}
Port-channel1.377: {admin-state: up, interface: Port-channel1.377, ip-add: 10.120.160.228,
  nameif: internal-vrf, netmask: 255.255.255.224, security-level: '100'}
