---

- name: ASA-RAS - Creating a changes directory for ACL configuration 'diff' files
  file:
    path: "{{ changes_dir }}"
    state: directory

# Retrieves current RAS ACLs and Group Policy Information
- name: ASA-RAS - Retrieving the pre-change ACL configuration
  asa_command:
    commands:
      - "show running-config access-list"
      - "show running-config group-policy"
  register: activeACL
  vars:
    ansible_command_timeout: 1000
    ansible_connect_timeout: 200   

#  Places information gathered in the task above into a temporary file for used in comparison
- name: ASA-RAS - Taking a snapshot of the pre_change ACL configuration
  template:
    src: "{{ role_path }}/templates/backup-template.j2"
    dest: "{{ pre_conf_file }}"
  changed_when: false
  vars:
    ansible_command_timeout: 1000
    ansible_connect_timeout: 200   