---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "./oob_inventory/dmvpn_hosts.yaml"
        group_file: "./oob_inventory/dmvpn_groups.yaml"
        defaults_file: "./oob_inventory/defaults.yaml"

logging:
    enabled: True

runner:
    plugin: threaded
    options:
        num_workers: 20