---

- name: IOS - Collecting the ACL configuration
  ios_command:
    commands:
      - show run | i access-list
  register: acl_output

- name: IOS - Collecting the named ACLs
  set_fact:
    named_acls: "{{ acl_output.stdout[0] | regex_findall('^ip\\s+access-list\\s+(?!logging)\\S+\\s+(?!CISCO)(?P<named_acls>\\S+)','\\g<named_acls>') }}"

- name: IOS - Collecting the numbered ACLs
  set_fact:
    num_acls: "{{ acl_output.stdout[0] | regex_findall('^access-list\\s(?P<num_acls>\\d+)','\\g<num_acls>') }}"

- name: IOS - Merging the named & numbered ACLs into a list
  set_fact:
    acls_yaml: "{{ acls_yaml|default([]) + named_acls + num_acls | unique }}"

- name: IOS - Collecting the ACLs configured
  ios_command:
    commands:
      - show access-lists {{ item }}
  with_items: 
  - "{{ acls_yaml }}"
  register: rules

- name: IOS - Parsing the ACL configuration
  command_parser:
    file: "/gitnet/ansible/parser_templates/ios/parser_ios_acl_yaml.yml"
    content: "{{ item.stdout[0] }}"
  with_items: 
  - "{{ rules.results }}"
  register: access_lists

- name: IOS - Creating a host directory for YAML files (if not already present)
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
    state: directory

- name: IOS - Generating the YAML file
  template:
    src: "/gitnet/ansible/roles/acl/templates/ios/yml-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/acl.yml"
