!
interface Tunnel500
 description LON - LON_DDOS_REF:5678
 ip address 50.50.50.1 255.255.255.252
 no ip redirects
 ip tcp adjust-mss 1436
 logging event link-status
 load-interval 10
 keepalive 10 3
 tunnel source 100.100.100.193
 tunnel destination 200.200.200.193
 hold-queue 1024 in
 hold-queue 1024 out
!

ip prefix-list ddos-lon-filter-in seq 100 deny 0.0.0.0/0 le 32
!
ip prefix-list ddos-lon-filter-out seq 100 permit 141.138.130.0/24
ip prefix-list ddos-lon-filter-out seq 100 permit 141.138.130.0/24
ip prefix-list ddos-lon-filter-out seq 101 permit 141.138.131.0/24
ip prefix-list ddos-lon-filter-out seq 102 permit 141.138.129.0/24
ip prefix-list ddos-lon-filter-out seq 103 permit 141.138.134.0/24
ip prefix-list ddos-lon-filter-out seq 104 permit 141.138.135.0/24
ip prefix-list ddos-lon-filter-out seq 105 permit 141.138.133.0/24
ip prefix-list ddos-lon-filter-out seq 106 permit 141.138.132.0/24
ip prefix-list ddos-lon-filter-out seq 1000 deny 0.0.0.0/0 le 32
!
ip prefix-list brs-frontend-prefix seq 10 permit 141.138.131.0/24
ip prefix-list brs-frontend-prefix seq 20 permit 141.138.129.0/24
ip prefix-list brs-frontend-prefix seq 30 permit 141.138.133.0/24
ip prefix-list brs-frontend-prefix seq 40 permit 141.138.134.0/24
ip prefix-list brs-frontend-prefix seq 50 permit 141.138.135.0/24
ip prefix-list brs-frontend-prefix seq 60 permit 141.138.132.0/24
!
ip prefix-list scc-frontend-prefix seq 10 permit 141.138.130.0/24
!


route-map ddos-lon-rm-in deny 10
!
route-map ddos-lon-rm-out permit 10
 match ip address prefix-list brs-frontend-prefix
 set community 2739058
!
route-map ddos-lon-rm-out permit 20
 match ip address prefix-list scc-frontend-prefix
 set community 2345677
!


!
router bgp 57002

 neighbor LON_PEER peer-group
 neighbor LON_PEER remote-as 5432
 neighbor LON_PEER password bgp_password
 neighbor LON_PEER timers 10 10
 neighbor 100.100.100.194 peer_group LON_PEER
 neighbor 100.100.100.194 description DDOS_LON

address-family ipv4
  neighbor LON_PEER send-community
  neighbor LON_PEER prefix-list ddos-lon-filter-in in
  neighbor LON_PEER prefix-list ddos-lon-filter-out out
  neighbor LON_PEER route-map ddos-lon-rm-in in
  neighbor LON_PEER route-map ddos-lon-rm-out out
  neighbor 100.100.100.194 activate
 exit-address-family
!