---

- name: IOS - Collect SSH Config
  ios_command:
    commands:
      - show run | include ip ssh
  register: ios_ssh_output

#- name: Display Output
#  debug: var=ios_ssh_output

- name: IOS - Parse Output
  command_parser:
    file: "/gitnet/ansible/parser_templates/ios/parser_ios_ssh.yml"
    content: "{{ ios_ssh_output.stdout.0 }}"

#- name: Display RAW output
#  debug: var=section

#- name: Display JSON Output
#  debug: var=ios_ssh_facts

- name: IOS - Generate CSV Report
  template:
    src: "/gitnet/ansible/roles/ssh/templates/ios/csv-template.j2"
    dest: "/gitnet/ansible/roles/ssh/files/{{ inventory_hostname }}.csv"
