---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/dbdev/vlan_hunter/inventory/hosts.yaml"
        group_file: "/dbdev/vlan_hunter/inventory/groups.yaml"
        defaults_file: "/dbdev/vlan_hunter/inventory/defaults.yaml"

logging:
    enabled: True

runner:
    plugin: threaded
    options:
        num_workers: 20