---

- name: IOS - Collecting the AAA configuration
  ios_command:
    commands:
      - show run
  register: raw_output

- name: IOS - Parsing the AAA configuration
  command_parser:
    file: "/gitnet/ansible/parser_templates/ios/parser_ios_aaa.yml"
    content: "{{ raw_output.stdout.0 }}"

- name: IOS - Creating a host directory for YAML files (if not already present)
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
    state: directory

- name: IOS - Generating the YAML file
  template:
    src: "/gitnet/ansible/roles/aaa/templates/ios/yml-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/aaa.yml"
