---

- name: NXOS - collect local user account info
  nxos_command:
    commands:
      - show run | in username
  register: nxos_local_accounts_output

- name: NXOS - parse command output
  command_parser:
    file: "{{ role_path }}/files/parser_templates/parser_nxos_local_user_accounts.yml"
    content: "{{ nxos_local_accounts_output.stdout.0 }}"

- name: NXOS - Generate csv report
  template:
    src: "{{ role_path }}/templates/nxos/csv-template.j2"
    dest: "{{ role_path }}/files/csv/nxos/{{ inventory_hostname }}.csv"