---

snmp_acl:
  - acl_num: "10"
    address:
      - "10.120.163.59"
  - acl_num: "11"
    remark: "SNMP write access"
    address:
      - "10.120.136.140"
      - "10.50.3.140"
  - acl_num: "12"
    address:
      - "10.180.163.111"
      - "10.180.163.112"
      - "10.120.163.111"
      - "10.120.163.112"


mgmt_acl:
  - 10.120.163.210
  - 10.1.74.66
  - 10.180.163.18
  - 10.53.33.56
  - 10.53.32.93
  - 10.210.163.60
  - 10.220.163.37
  - 10.1.74.29
  - 10.53.33.120
  - 10.53.33.119
  - 10.1.74.48
  - 10.53.32.110
  - 10.53.32.107
  - 10.1.74.57
  - 10.1.74.61
  - 10.53.32.133
  - 10.17.144.32
  - 10.120.195.31
  - 10.120.143.70
  - 10.220.142.230
  - 10.1.74.128
  - 10.17.100.187
  - 10.180.142.230
  - 10.120.163.37
  - 10.1.82.64 0.0.0.31
  - 10.1.82.160 0.0.0.31
  - 10.1.22.0 0.0.0.255
  - 172.16.41.208 0.0.0.15
  - 172.16.64.16 0.0.0.7
  - 192.168.2.0 0.0.1.255


snmp:
  communities:
    - community: "m0squ1t0"
      snmp_svr: "10.120.163.59"
      type: "ro"
      acl: "10"
    - community: "wh1LLc0rp"
      snmp_svr: "10.120.163.59"
      type: "rw"
      acl: "11"
    - community: "n1m50ft"
      snmp_svr: "10.120.163.59"
      type: "ro"
      acl: "12"

line_vty:
  line_num:
    - "0 4"
    - "5 15"
  vty_acl: "1"
  timeout_mins: "15"
  transport_input: "ssh"

ssh:
  ssh_timeout: "5"
  ssh_ver: "2"


local_admin:
  name: "netadmin"
  secret_5: "$1$0z2p$jbtbcHYIh7rq7MdERPNjp/"


enable_secret_5: "$1$sYrB$EJIkMToVDrVW6JL0b96WW."


aaa:
  group:
    - name: "WH-ACS-TACACS"
      type: "tacacs+"
      vrf: "group-vrf"
      source_int: "Loopback20"
      server_list:
        - name: SCC-ACS
          type: tacacs
          addr: "10.120.163.26"
          key_7 : "023F014A2A282519646602183C27015806"
        - name: BRS-ACS
          type: tacacs
          addr: "10.210.163.26"
          key_7 : "04620E172E0F667621310E162B3B1F5720"

ntp:
  source_int: "Loopback20"
  server:
    - vrf: "group-vrf"
      addr: "10.120.163.20"
    - vrf: "group-vrf"
      addr: "10.120.163.20"
      
boot_image:
  #Ordered list
  - c6880x-adventerprisek9-mz.SPA.152-1.SY4.bin
  - c6880x-adventerprisek9-mz.SPA.152-1.SY2.bin
  
