---
- name: Execute Configuration of DST
  block:
    - name: ASA-RAS-SYNC - Check Which Device is Live
      shell: dig +short vpn.williamhillplc.com
      register: vpn_nslookup
      check_mode: no

    - name: Point to secondary
      set_fact:
        primary_host: "{% if (vpn_nslookup.stdout.startswith('10.120') or vpn_nslookup.stdout.startswith('141.138')) %}{{ groups[lookup('vars', 'ma3_sync_group')][0] }}{% else %}{{ groups[lookup('vars', 'ld6_sync_group')][0] }}{% endif %}"

    # - name: ASA-RAS - VPN YAML creation task
    #   # include_tasks: asa-ras-dst-yaml.yml
    #   # when:
    #   #   - type == "ras"

    - name: ASA-RAS - Validate and deploy ansible data file for current DST
      include_tasks: asa-ras-dst-validation.yml
      when:
        - type is defined and type == "ras" and inventory_hostname == primary_host

    # This takes a snapshot of the ACLs and group policy configuration and places in a temporary file. It is then used to identify what has changed.
    - name: ASA-RAS - Taking pre-change snapshot
      include_tasks: pre-change-snapshot.yml
      when:
        - type is defined and type == "ras" and inventory_hostname == primary_host

    # Apply new RAS configuration to the devices, then produces a text file output showing what has changed
    - name: ASA-RAS - Apply configuration to device for RAS DST
      include_tasks: asa-ras-dst-config.yml
      when:
        - type is defined and type == "ras" and inventory_hostname == primary_host

    - name: Force Handlers Run
      meta: flush_handlers
      check_mode: no


  rescue:
    - name: For Run of Cleanup after Failure
      shell: "echo '\e[1;32m############################################ \nStarting Failure Handling Process\n############################################ \e[0m'"
      notify: "fail_executed"
      check_mode: no

    - name: Force Handlers Run
      meta: flush_handlers
      check_mode: no
