---

  - name: PLAY - EPG to Domain query
    hosts: aci
    connection: local
    gather_facts: no


    tasks:
    
    - name: Query EPG to Domain association
      aci_epg_to_domain:
        hostname: '{{ ansible_host }}'
        username: '{{ aci_user }}'
        private_key: '{{ aci_key }}'
        state: query
        validate_certs: no
        
      register: imdata_epg_to_domain
      

    - name: Output to table
      template:
        src: ./templates/epg_to_domain_table.j2
        dest: ./reports/epg-to-domain_{{ inventory_hostname }}.md
      with_items:
        - "{{ imdata_epg_to_domain }} "

