Port-channel1.1620: {admin-state: up, interface: Port-channel1.1620, ip-add: 10.61.160.68,
  mac-address: 000a.f22c.1111, nameif: common-default-vrf, netmask: 255.255.255.224,
  security-level: '100'}
Port-channel1.1621: {admin-state: up, interface: Port-channel1.1621, ip-add: 10.19.32.129,
  mac-address: 000b.f22c.1111, nameif: common-group-vrf, netmask: 255.255.255.224,
  security-level: '100'}
Port-channel1.1622: {admin-state: up, interface: Port-channel1.1622, ip-add: 10.61.160.1,
  mac-address: 000c.f22c.0111, nameif: common-internal-vrf, netmask: 255.255.255.224,
  security-level: '100'}
