---

- name: ASA-SINGLE - Retrieving the management access configuration
  asa_command:   
    commands:  
      - "show running-config ssh"
      - "show running-config http"
  register: mgmtACL

- name: ASA-SINGLE - Registering the configuration lines that are to be removed
  set_fact:
    sshACC: "{{ mgmtACL.stdout[0] | regex_findall('(.*10.120.163.*)') }}"
    httpACC: "{{ mgmtACL.stdout[1] | regex_findall('(.*10.120.163.*)') }}"

#- name: ASA-SINGLE - Building the configuration for testing purposes
#  template:
#    src: "{{ role_path }}/templates/asa-deletions.j2"
#    dest: "{{ role_path }}/files/configs/asa/{{ inventory_hostname }}.cfg"
#  when: sshACC or httpACC

- name: ASA-SINGLE - Building and applying the configuration
  asa_config:
    src: "{{ role_path }}/templates/asa-deletions.j2"
    save: yes
  register: mgmtUPDATED
  notify: "updates exist"
  when: sshACC or httpACC