---

snmp:
  contact: Network Services
  communities:
    - community: m0squ1t0
      snmp_svr: "10.120.163.59"
      type: ro
      acl: "10"
    - community: wh1LLc0rp
      snmp_svr: "10.120.163.59"
      type: rw
      acl: "11"
    - community: n1m50ft
      snmp_svr: "10.120.163.59"
      type: ro
      acl: "12"

      
ssh:
  ssh_timeout: "5"
  ssh_ver: "2"
