---
## Import the dfw_sddc_specific_groups variables if running this task standalone
- name: Import the dfw_sddc_specific_groups variables if running this task standalone
  include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/dfw_sddc_specific_groups.yml"

## Confirm Directory Exisits
- name: ASA-SINGLE - Create directory for YAML files if not present
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
    state: directory

# Following 2 tasks place the details in the terraform .tf files 
- name: ASA-SINGLE - Generate VMC Terraform file - Network Objects (groups)
  template:
    src: /gitnet/ansible/roles/vmc-conversions/templates/asa_single/dfw_sddc_specific_groups_tf.j2
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/dfw_sddc_specific_groups.tf"