---

## Confirm Directory Exisits
- name: ASA-SINGLE - Create directory for YAML files if not present
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
    state: directory

# Following task places the Service and Protocol Objects (ports) in the terraform .tf files 
- name: ASA-SINGLE - Generate VMC Terraform file - Service and Protocol Objects (ports)
  template:
    src: /gitnet/ansible/roles/vmc-conversions/templates/asa_single/dfw_sddc_specific_ports_tf.j2
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/dfw_sddc_specific_ports.tf"
