
  - app_prof: 'pr-c-frontend'
    tenant: 'production'
    vrf: 'pr-c-frontend'
    bds:
      - bd: 'pr-c-frontend_cde-app'
        network: '10.120.32.64'
        gateway: '10.120.32.65'
        mask: '255.255.255.224'
        cidr_mask: '27'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_cde-app'
            encap_id: '102'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_mailhosts'
        network: '10.120.33.160'
        gateway: '10.120.33.161'
        mask: '255.255.255.224'
        cidr_mask: '27'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_mailhosts'
            encap_id: '115'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_cde-web-new'
        network: '10.120.37.0'
        gateway: '10.120.37.1'
        mask: '255.255.255.0'
        cidr_mask: '24'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_cde-web-new'
            encap_id: '121'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_cde-backoffice-new'
        network: '10.120.38.0'
        gateway: '10.120.38.1'
        mask: '255.255.255.0'
        cidr_mask: '24'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_cde-backoffice-new'
            encap_id: '122'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_citrix'
        network: '10.120.39.0'
        gateway: '10.120.39.1'
        mask: '255.255.255.0'
        cidr_mask: '24'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_citrix'
            encap_id: '123'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_int-lb'
        network: '10.120.44.0'
        gateway: '10.120.44.1'
        mask: '255.255.254.0'
        cidr_mask: '23'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_int-lb'
            encap_id: '134'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_storage_data'
        network: '10.120.46.0'
        gateway: '10.120.46.1'
        mask: '255.255.255.128'
        cidr_mask: '25'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_storage_data'
            encap_id: '140'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_hdr-db'
        network: '10.120.48.96'
        gateway: '10.120.48.97'
        mask: '255.255.255.224'
        cidr_mask: '27'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_hdr-db'
            encap_id: '154'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_cde-app-new'
        network: '10.120.50.0'
        gateway: '10.120.50.1'
        mask: '255.255.255.0'
        cidr_mask: '24'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_cde-app-new'
            encap_id: '160'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_database'
        network: '10.120.52.0'
        gateway: '10.120.52.1'
        mask: '255.255.255.0'
        cidr_mask: '24'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_database'
            encap_id: '162'
            vcenter_dynamic_vlan: true
      - bd: 'pr-c-frontend_internal-vrf'
        network: '10.120.160.32'
        gateway: '10.120.160.36'
        mask: '255.255.255.224'
        cidr_mask: '27'
        scope: 'shared'
        l3_ownership: firewall
        epgs:
          - epg: 'pr-c-frontend_internal-vrf'
            encap_id: '371'
            vcenter_dynamic_vlan: true