---


## Future changes
## - Check if CDP is enabled, enable if disabled, run and disable

- name: IOS - Import Network Parser role
  include_role:
    name: clay584.parse_genie
  run_once: true

- name: IOS - Create an inventory directory if it does not exist
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
    state: directory

- name: NXOS - Create a ios template directory if it does not exist
  file:
    path: "{{ role_path }}/templates/ios"
    state: directory  


- name: IOS - Run the show interfaces description
  ios_command:
    commands:
      - show interfaces description
  register: output_int_description

- name: IOS - Set fact with Genie filter plugin
  set_fact:
    pyats_version: "{{ output_int_description['stdout'][0] | parse_genie(command='show interfaces description', os='ios') }}"

# Create YAML, CSV and MD file with results #
- name: IOS - Export interface descriptions to YAML
  template:
    src: "{{ role_path }}/templates/ios/int-desc-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/interface-dataset.yml"

- name: IOS - Run the show cdp neighbors
  ios_command:
    commands:
      - show cdp neighbors
  register: output_cdp_neighbors

- name: IOS - Set fact with Genie filter plugin
  set_fact:
    pyats_version: "{{ output_cdp_neighbors['stdout'][0] | parse_genie(command='show cdp neighbors', os='ios') }}"

- name: IOS - Export the entire CDP database to YAML 
  template:
    src: "{{ role_path }}/templates/ios/cdp-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/cdp-dataset.yml"

- name: IOS - Refreshing cdp-information variables generated by the above tasks in order to service any subsequent tasks
  include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/{{ item }}.yml"
  loop:
    - cdp-dataset
    - interface-dataset

- name: IOS - Build final YAML dataset for the CSV based on Up Interfaces, No Description and a CDP relationship
  template:
    src: "{{ role_path }}/templates/ios/final-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/final-dataset.yml"
  when: interface_description_state is iterable 

- name: IOS - Build final YAML dataset for config data on Up Interfaces, No Description and a CDP relationship
  template:
    src: "{{ role_path }}/templates/ios/config-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/config-dataset.yml"
  when: interface_description_state is iterable 

- name: IOS - Refreshing interface-description variables generated by the above tasks in order to service any subsequent tasks
  include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/final-dataset.yml"
  when: final_state is defined 

- name: IOS - Create a directory if it does not exist
  file:
    path: "/{{ role_path }}/files/csv/ios/"
    state: directory

- name: IOS - Generate csv report
  template:
    src: "{{ role_path }}/templates/ios/csv-template.j2"
    dest: "{{ role_path }}/files/csv/ios/{{ inventory_hostname }}.csv"
  when: final_state is defined 

- name: IOS - Cleaning Staging Files. Deleting - cdp-information, interface-dataset, final-dataset 
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/{{ item }}.yml"
    state: absent
  loop:
    - cdp-information
    - interface-dataset
    - final-dataset

#- name: Debug PyATS facts
#  debug:
#    var: pyats_version | type_debug

#- name: Debug pyATS facts - uptime
#  debug:
#   var: pyats_version.version.uptime
