---

- name: NXOS - Import Network Parser role
  include_role:
    name: clay584.parse_genie
  run_once: true

- name: NXOS - Create an inventory directory if it does not exist
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
    state: directory

- name: NXOS - Create a nxos template directory if it does not exist
  file:
    path: "{{ role_path }}/templates/nxos"
    state: directory  

- name: NXOS - Run the show interface status
  ios_command:
    commands:
      - show interface status
  register: output_int_status

- name: NXOS - Set fact with Genie filter plugin
  set_fact:
    pyats_version: "{{ output_int_status['stdout'][0] | parse_genie(command='show interface status', os='nxos') }}"

## pass the above into a jinja2 template to build a yml structured interface descrption list.

- name: NXOS - Interface status to YAML
  template:
    src: "{{ role_path }}/templates/nxos/int-status-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/interface-state.yml"
    #no_log: true

- name: NXOS - Run the show interfaces description
  ios_command:
    commands:
      - show interface description
  register: output_int_description

- name: NXOS - Set fact with Genie filter plugin
  set_fact:
    pyats_version: "{{ output_int_description['stdout'][0] | parse_genie(command='show interface description', os='nxos') }}"

## pass the above into a jinja2 template to build a yml structured interface descrption list.

- name: NXOS - Refreshing interface-state variables generated by the above tasks in order to service any subsequent tasks
  include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/interface-state.yml"

- name: NXOS - Export interfaces with no descriptions to YAML based on interface state - Connected 
  template:
    src: "{{ role_path }}/templates/nxos/int-desc-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/interface-dataset.yml"

- name: NXOS - Deleting interface-state file 
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/interface-state.yml"
    state: absent
#
- name: NXOS - Run the show cdp neighbors
  ios_command:
    commands:
      - show cdp neighbors
  register: output_cdp_neighbors

- name: NXOS - Set fact with Genie filter plugin
  set_fact:
    pyats_version: "{{ output_cdp_neighbors['stdout'][0] | parse_genie(command='show cdp neighbors', os='ios') }}"

- name: NXOS - Export the entire CDP database to YAML 
  template:
    src: "{{ role_path }}/templates/nxos/cdp-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/cdp-dataset.yml"
    #no_log: true

- name: IOS - Refreshing cdp-information variables generated by the above tasks in order to service any subsequent tasks
  include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/{{ item }}.yml"
  loop:
    - cdp-dataset
    - interface-dataset

- name: NXOS - Build final YAML dataset for the CSV based on Up Interfaces, No Description and a CDP relationship
  template:
    src: "{{ role_path }}/templates/nxos/final-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/final-dataset.yml"
  when: interface_description_state is iterable

- name: NXOS - Build final YAML dataset for config data based on Up Interfaces, No Description and a CDP relationship
  template:
    src: "{{ role_path }}/templates/nxos/config-template.j2"
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/config-dataset.yml"
  when: interface_description_state is iterable

- name: NXIS - Refreshing interface-description variables generated by the above tasks in order to service any subsequent tasks
  include_vars:
    file: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/final-dataset.yml"
  when: final_state is defined 

- name: NXOS - Create a directory if it does not exist
  file:
    path: "/{{ role_path }}/files/csv/nxos/"
    state: directory

- name: NXOS - Generate csv report
  template:
    src: "{{ role_path }}/templates/nxos/csv-template.j2"
    dest: "{{ role_path }}/files/csv/nxos/{{ inventory_hostname }}.csv"
  when: final_state is defined 

- name: NXOS - Cleaning Staging Files. Deleting - cdp-dataset, interface-dataset, final-dataset 
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/{{ item }}.yml"
    state: absent
  loop:
    - cdp-dataset
    - interface-dataset
    - final-dataset


#- name: Debug PyATS facts
#  debug:
#    var: pyats_version | type_debug
