---

- name: IOS - collect VTY info
  ios_command:
    commands:
      - show run | section vty
  register: ios_vty_output

# Debug commands to check output
#- name: Display output
#  debug: var=ios_vty_output

- name: IOS - parse command output
  command_parser:
    file: /gitnet/ansible/parser_templates/ios/vty.yml
    content: "{{ ios_vty_output.stdout.0 }}"

# Debug commands to check output
#- name: Display JSON output
#  debug: var=ios_vty_facts

- name: IOS - Create directory for YAML files if not present
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
    state: directory

- name: IOS - Generate YAML file
  template:
    src: /gitnet/ansible/roles/vty/templates/ios/yml-template.j2
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/vty.yml"
