---

- name: IOS-XR - collect VTY info
  iosxr_command:
    commands:
      - show run
  register: iosxr_vty_output

# Debug commands to check output
#- name: Display output
#  debug: var=iosxr_vty_output

- name: IOS-XR - parse command output
  command_parser:
    file: /gitnet/ansible/parser_templates/iosxr/vty.yml
    content: "{{ iosxr_vty_output.stdout.0 }}"


- name: IOS-XR - Create directory for YAML files if not present
  file:
    path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
    state: directory

- name: IOS-XR - Generate YAML file
  template:
    src: /gitnet/ansible/roles/vty/templates/iosxr/yml-template.j2
    dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/vty.yml"
