---

- name: Create a Tenant level Snapshot
  aci_config_snapshot:
    hostname: '{{ ansible_host }}'
    username: '{{ aci_user }}'
    private_key: '{{ aci_key }}'
    state: present
    export_policy: ansible_backup
    description: '{{ snapshot_description }}'
    validate_certs: no
