---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "./retail_inventory/hosts.yaml"
        group_file: "./retail_inventory/groups.yaml"
        defaults_file: "./retail_inventory/global_defaults.yaml"

logging:
    enabled: True

runner:
    plugin: threaded
    options:
        num_workers: 20