---
jira_api_url: "https://evokeplc.atlassian.net/rest/api/2/issue/{{ change_reference }}/comment"
tools_path: "/gitnet/evoke_cloud/wh_net_python_toolset"
log_path: "./log/"
log_file_prefix: "{{ now(utc=true,fmt='%Y_%m_%d_%H_%M') }}_"
python_log_level: "notice"

subnet_converstion:
  - range: "1-9 (28)"
    cidr: "28"
  - range: "10-25 (27)"
    cidr: "27"
  - range: "26-57 (26)"
    cidr: "26"
  - range: "58-121 (25)"
    cidr: "25"
  - range: "122-249 (24)"
    cidr: "24"
  - range: "250-505 (23)"
    cidr: "23"
  - range: "506-1017 (22)"
    cidr: "22"
  - range: "1018-2041 (21)"
    cidr: "21"
  - range: "2042-4089 (20)"
    cidr: "20"