Port-channel21.1503: {admin-state: up, interface: Port-channel21.1503, ip-add: 10.211.131.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1504: {admin-state: up, interface: Port-channel21.1504, ip-add: 10.211.132.1,
  nameif: applications-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1505: {admin-state: up, interface: Port-channel21.1505, ip-add: 10.211.133.1,
  nameif: database-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1506: {admin-state: up, interface: Port-channel21.1506, ip-add: 10.211.134.1,
  nameif: citrix-tier, netmask: 255.255.255.128, security-level: '100'}
Port-channel21.1510: {admin-state: up, interface: Port-channel21.1510, ip-add: 10.211.137.1,
  nameif: backoffice-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1520: {admin-state: up, interface: Port-channel21.1520, ip-add: 10.211.140.1,
  nameif: Stingray-ADS-Servers, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1534: {admin-state: up, interface: Port-channel21.1534, ip-add: 10.211.143.65,
  nameif: sftp-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.1538: {admin-state: up, interface: Port-channel21.1538, ip-add: 10.211.143.193,
  nameif: crypto-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.1575: {admin-state: up, interface: Port-channel21.1575, ip-add: 10.211.160.164,
  nameif: pp1off-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
