Port-channel21.1301: {admin-state: up, interface: Port-channel21.1301, ip-add: 10.211.32.33,
  nameif: non-cde-web-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.1311: {admin-state: up, interface: Port-channel21.1311, ip-add: 10.211.33.33,
  nameif: non-cde-backoffice-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.1431: {admin-state: up, interface: Port-channel21.1431, ip-add: 10.211.74.1,
  nameif: int-lb, netmask: 255.255.254.0, security-level: '100'}
Port-channel21.1622: {admin-state: up, interface: Port-channel21.1622, ip-add: 10.211.224.4,
  nameif: pp1off-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
