Port-channel21.2041: {admin-state: up, interface: Port-channel21.2041, ip-add: 10.212.145.1,
  nameif: proxy-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2042: {admin-state: up, interface: Port-channel21.2042, ip-add: 10.212.146.1,
  nameif: applications-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2043: {admin-state: up, interface: Port-channel21.2043, ip-add: 10.212.147.1,
  nameif: applications2-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2044: {admin-state: up, interface: Port-channel21.2044, ip-add: 10.212.148.1,
  nameif: backoffice-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2045: {admin-state: up, interface: Port-channel21.2045, ip-add: 10.212.149.1,
  nameif: ODS-mgmt-servers, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2066: {admin-state: up, interface: Port-channel21.2066, ip-add: 10.212.159.129,
  nameif: ODS-mgmt, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2076: {admin-state: up, interface: Port-channel21.2076, ip-add: 10.212.160.196,
  nameif: pp1on-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
