Port-channel21.1896: {admin-state: up, interface: Port-channel21.1896, ip-add: 10.212.183.1,
  nameif: retail-web, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.1946: {admin-state: up, interface: Port-channel21.1946, ip-add: 10.212.172.1,
  nameif: retail-ssbt, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2084: {admin-state: up, interface: Port-channel21.2084, ip-add: 10.212.161.196,
  nameif: pp1on-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.71: {admin-state: up, interface: Port-channel21.71, ip-add: 10.64.73.36,
  nameif: wan, netmask: 255.255.255.224, security-level: '100'}
