Port-channel21.2330: {admin-state: up, interface: Port-channel21.2330, ip-add: 10.213.40.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2350: {admin-state: up, interface: Port-channel21.2350, ip-add: 10.213.48.1,
  nameif: proxy-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2351: {admin-state: up, interface: Port-channel21.2351, ip-add: 10.213.48.33,
  nameif: backoffice-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2352: {admin-state: up, interface: Port-channel21.2352, ip-add: 10.213.48.65,
  nameif: authpro-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2353: {admin-state: up, interface: Port-channel21.2353, ip-add: 10.213.48.97,
  nameif: sftp-ext-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2355: {admin-state: up, interface: Port-channel21.2355, ip-add: 10.213.48.161,
  nameif: crypto-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2360: {admin-state: up, interface: Port-channel21.2360, ip-add: 10.213.50.1,
  nameif: application-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2362: {admin-state: up, interface: Port-channel21.2362, ip-add: 10.213.52.1,
  nameif: database-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2501: {admin-state: up, interface: Port-channel21.2501, ip-add: 10.213.129.44,
  nameif: management, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2573: {admin-state: up, interface: Port-channel21.2573, ip-add: 10.213.160.100,
  nameif: pp2off-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
