Port-channel21.2541: {admin-state: up, interface: Port-channel21.2541, ip-add: 10.213.145.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2542: {admin-state: up, interface: Port-channel21.2542, ip-add: 10.213.146.1,
  nameif: applications-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2544: {admin-state: up, interface: Port-channel21.2544, ip-add: 10.213.148.1,
  nameif: backoffice-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2561: {admin-state: up, interface: Port-channel21.2561, ip-add: 10.213.158.1,
  nameif: caerus-apps-man-2, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.2566: {admin-state: up, interface: Port-channel21.2566, ip-add: 10.213.159.129,
  nameif: rng-retail-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2569: {admin-state: up, interface: Port-channel21.2569, ip-add: 10.213.159.225,
  nameif: caerus-app-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2576: {admin-state: up, interface: Port-channel21.2576, ip-add: 10.213.160.196,
  nameif: pp2off-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
