Port-channel21.2896: {admin-state: up, interface: Port-channel21.2896, ip-add: 10.214.183.1,
  nameif: retail-web, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.2946: {admin-state: up, interface: Port-channel21.2946, ip-add: 10.214.172.1,
  nameif: retail-ssbt, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3084: {admin-state: up, interface: Port-channel21.3084, ip-add: 10.214.161.196,
  nameif: pp2on-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.73: {admin-state: up, interface: Port-channel21.73, ip-add: 10.64.73.4,
  nameif: wan, netmask: 255.255.255.224, security-level: '100'}
