Port-channel21.3503: {admin-state: up, interface: Port-channel21.3503, ip-add: 10.215.131.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3504: {admin-state: up, interface: Port-channel21.3504, ip-add: 10.215.132.1,
  nameif: applications-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3505: {admin-state: up, interface: Port-channel21.3505, ip-add: 10.215.133.1,
  nameif: database-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3506: {admin-state: up, interface: Port-channel21.3506, ip-add: 10.215.134.1,
  nameif: citrix-tier, netmask: 255.255.255.128, security-level: '100'}
Port-channel21.3510: {admin-state: up, interface: Port-channel21.3510, ip-add: 10.215.137.1,
  nameif: backoffice-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3520: {admin-state: up, interface: Port-channel21.3520, ip-add: 10.215.140.1,
  nameif: Stingray-ADS-Management, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3534: {admin-state: up, interface: Port-channel21.3534, ip-add: 10.215.143.65,
  nameif: sftp-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.3538: {admin-state: up, interface: Port-channel21.3538, ip-add: 10.215.143.193,
  nameif: crypto-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.3575: {admin-state: up, interface: Port-channel21.3575, ip-add: 10.215.160.164,
  nameif: pp3off-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
