Port-channel21.3330: {admin-state: up, interface: Port-channel21.3330, ip-add: 10.215.40.1,
  nameif: web-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3350: {admin-state: up, interface: Port-channel21.3350, ip-add: 10.215.48.1,
  nameif: proxy-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.3351: {admin-state: up, interface: Port-channel21.3351, ip-add: 10.215.48.33,
  nameif: backoffice-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.3352: {admin-state: up, interface: Port-channel21.3352, ip-add: 10.215.48.65,
  nameif: authpro-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.3353: {admin-state: up, interface: Port-channel21.3353, ip-add: 10.215.48.97,
  nameif: sftp-ext-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.3355: {admin-state: up, interface: Port-channel21.3355, ip-add: 10.215.48.161,
  nameif: crypto-tier, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.3360: {admin-state: up, interface: Port-channel21.3360, ip-add: 10.215.50.1,
  nameif: application-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3362: {admin-state: up, interface: Port-channel21.3362, ip-add: 10.215.52.1,
  nameif: database-tier, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.3573: {admin-state: up, interface: Port-channel21.3573, ip-add: 10.215.160.100,
  nameif: pp3off-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
