Port-channel21.4080: {admin-state: up, interface: Port-channel21.4080, ip-add: 10.216.161.68,
  nameif: pp3on-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.4081: {admin-state: up, interface: Port-channel21.4081, ip-add: 10.216.162.1,
  nameif: almbuild-int, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.4082: {admin-state: up, interface: Port-channel21.4082, ip-add: 10.216.163.1,
  nameif: monitoring-int, netmask: 255.255.255.0, security-level: '100'}
