Port-channel21.1584: {admin-state: up, interface: Port-channel21.1584, ip-add: 10.211.161.196,
  nameif: pp1off-internal-vrf, netmask: 255.255.255.224, security-level: '100'}
Port-channel21.1708: {admin-state: up, interface: Port-channel21.1708, ip-add: 10.191.1.1,
  nameif: pp1off-cde-deployment-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1709: {admin-state: up, interface: Port-channel21.1709, ip-add: 10.191.2.1,
  nameif: pp1off-cde-web1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1710: {admin-state: up, interface: Port-channel21.1710, ip-add: 10.191.3.1,
  nameif: pp1off-cde-app1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1711: {admin-state: up, interface: Port-channel21.1711, ip-add: 10.191.4.1,
  nameif: pp1off-cde-internal-presentation, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1712: {admin-state: up, interface: Port-channel21.1712, ip-add: 10.191.5.1,
  nameif: pp1off-cde-api-integration, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1713: {admin-state: up, interface: Port-channel21.1713, ip-add: 10.191.6.1,
  nameif: pp1off-cde-ext-pres-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1714: {admin-state: up, interface: Port-channel21.1714, ip-add: 10.191.7.1,
  nameif: pp1off-cde-ext-api, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1715: {admin-state: up, interface: Port-channel21.1715, ip-add: 10.191.8.1,
  nameif: pp1off-cde-lan02, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1716: {admin-state: up, interface: Port-channel21.1716, ip-add: 10.191.9.1,
  nameif: pp1off-cde-lan03, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1717: {admin-state: up, interface: Port-channel21.1717, ip-add: 10.191.10.1,
  nameif: pp1off-c-front-cx-mgmt, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1718: {admin-state: up, interface: Port-channel21.1718, ip-add: 10.191.11.1,
  nameif: pp1off-cde-lan04, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1719: {admin-state: up, interface: Port-channel21.1719, ip-add: 10.191.12.1,
  nameif: pp1off-cde-lan05, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1720: {admin-state: up, interface: Port-channel21.1720, ip-add: 10.191.13.1,
  nameif: pp1off-cde-lan06, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1721: {admin-state: up, interface: Port-channel21.1721, ip-add: 10.191.14.1,
  nameif: pp1off-cde-lan07, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1722: {admin-state: up, interface: Port-channel21.1722, ip-add: 10.191.15.1,
  nameif: pp1off-cde-lan08, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1723: {admin-state: up, interface: Port-channel21.1723, ip-add: 10.191.16.1,
  nameif: pp1off-cde-lan09, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1724: {admin-state: up, interface: Port-channel21.1724, ip-add: 10.191.17.1,
  nameif: pp1off-cde-lan10, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1725: {admin-state: up, interface: Port-channel21.1725, ip-add: 10.191.18.1,
  nameif: pp1off-cde-lan11, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1726: {admin-state: up, interface: Port-channel21.1726, ip-add: 10.191.19.1,
  nameif: pp1off-cde-lan12, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1727: {admin-state: up, interface: Port-channel21.1727, ip-add: 10.191.20.1,
  nameif: pp1off-cde-lan13, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1728: {admin-state: up, interface: Port-channel21.1728, ip-add: 10.191.21.1,
  nameif: pp1off-cde-lan14, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1729: {admin-state: up, interface: Port-channel21.1729, ip-add: 10.191.22.1,
  nameif: pp1off-cde-lan15, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1730: {admin-state: up, interface: Port-channel21.1730, ip-add: 10.191.23.1,
  nameif: pp1off-cde-lan16, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1758: {admin-state: up, interface: Port-channel21.1758, ip-add: 10.191.65.1,
  nameif: pp1off-noncde-deployment-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1759: {admin-state: up, interface: Port-channel21.1759, ip-add: 10.191.66.1,
  nameif: pp1off-noncde-web1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1760: {admin-state: up, interface: Port-channel21.1760, ip-add: 10.191.67.1,
  nameif: pp1off-noncde-app1-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1761: {admin-state: up, interface: Port-channel21.1761, ip-add: 10.191.68.1,
  nameif: pp1off-noncde-lan01, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1762: {admin-state: up, interface: Port-channel21.1762, ip-add: 10.191.69.1,
  nameif: pp1off-noncde-lan02, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1763: {admin-state: up, interface: Port-channel21.1763, ip-add: 10.191.70.1,
  nameif: pp1off-noncde-lan03, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1764: {admin-state: up, interface: Port-channel21.1764, ip-add: 10.191.71.1,
  nameif: pp1off-noncde-lan04, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1765: {admin-state: up, interface: Port-channel21.1765, ip-add: 10.191.72.1,
  nameif: pp1off-noncde-lan05, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1766: {admin-state: up, interface: Port-channel21.1766, ip-add: 10.191.73.1,
  nameif: pp1off-noncde-lan06, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1767: {admin-state: up, interface: Port-channel21.1767, ip-add: 10.191.74.1,
  nameif: pp1off-noncde-lan07, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1768: {admin-state: up, interface: Port-channel21.1768, ip-add: 10.191.75.1,
  nameif: pp1off-noncde-lan08, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1769: {admin-state: up, interface: Port-channel21.1769, ip-add: 10.191.76.1,
  nameif: pp1off-noncde-lan09, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1770: {admin-state: up, interface: Port-channel21.1770, ip-add: 10.191.77.1,
  nameif: pp1off-noncde-lan10, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1771: {admin-state: up, interface: Port-channel21.1771, ip-add: 10.191.78.1,
  nameif: pp1off-noncde-app2-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1772: {admin-state: up, interface: Port-channel21.1772, ip-add: 10.191.79.1,
  nameif: pp1off-noncde-app3-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1773: {admin-state: up, interface: Port-channel21.1773, ip-add: 10.191.80.1,
  nameif: pp1off-noncde-app4-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1774: {admin-state: up, interface: Port-channel21.1774, ip-add: 10.191.81.1,
  nameif: pp1off-noncde-app5-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1775: {admin-state: up, interface: Port-channel21.1775, ip-add: 10.191.82.1,
  nameif: pp1off-noncde-app6-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1776: {admin-state: up, interface: Port-channel21.1776, ip-add: 10.191.83.1,
  nameif: pp1off-noncde-app7-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1777: {admin-state: up, interface: Port-channel21.1777, ip-add: 10.191.84.1,
  nameif: pp1off-noncde-app8-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1778: {admin-state: up, interface: Port-channel21.1778, ip-add: 10.191.85.1,
  nameif: pp1off-noncde-app9-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1779: {admin-state: up, interface: Port-channel21.1779, ip-add: 10.191.86.1,
  nameif: pp1off-noncde-app10-lan, netmask: 255.255.255.0, security-level: '100'}
Port-channel21.1780: {admin-state: up, interface: Port-channel21.1780, ip-add: 10.191.87.1,
  nameif: pp1off-noncde-app11-lan, netmask: 255.255.255.0, security-level: '100'}
