---

- name: parser meta data
  parser_metadata:
    version: 1.0
    command: "show run object-group protocol"
    network_os: asa

- name: protocol-object group_name match pattern
  pattern_match:
    regex: "^object-group protocol \\S+"
    match_all: yes
    match_greedy: yes
  register: group_name

- name: protocol-object object match pattern
  pattern_match:
    regex: "^ protocol-object \\S+"
    match_all: yes
    match_greedy: yes
  register: protocol_object_objects

- name: protocol-object group-object match pattern
  pattern_match:
    regex: "^ group-object \\S+"
    match_all: yes
    match_greedy: yes
  register: protocol_object_group_objects

- name: description match pattern
  pattern_match:
    regex: "^ description .*\\n"
    match_all: yes
    match_greedy: yes
  register: group_description

- name: Match object-group name
  pattern_group:
    - name: match name
      pattern_match:
        regex: "^object-group protocol (\\S+)"
        content: "{{ item }}"
      register: name

  loop: "{{ group_name }}"
  register: object_group_name 

- name: Match object-group description
  pattern_group:
    - name: match name
      pattern_match:
        regex: "^ description (.*)\\n"
        content: "{{ item }}"
      register: description

  loop: "{{ group_description }}"
  register: group_description_value 

- name: Match protocol-object object values
  pattern_group:
    - name: match name
      pattern_match:
        regex: "^ protocol-object (\\S+)"
        content: "{{ item }}"
      register: name

  loop: "{{ protocol_object_objects }}"
  register: protocol_object_objects_group

- name: Match protocol-object group-object values
  pattern_group:
    - name: match name
      pattern_match:
        regex: "^ group-object (\\S+)"
        content: "{{ item }}"
      register: name

  loop: "{{ protocol_object_group_objects }}"
  register: protocol_object_group_objects_group   

- name: Generate group name JSON data structure - 
  json_template:
    template:
      - key: name
        value: "{{ item.name.matches.0 }}"      
  loop: "{{ object_group_name }}"
  export: yes
  register: object_group

- name: Generate group name JSON data structure - 
  json_template:
    template:
      - key: description
        value: "{{ item.description.matches.0 }}"       
  loop: "{{ group_description_value }}"
  export: yes
  register: object_group_description

- name: Generate group-object object JSON data structure - 
  json_template:
    template:       
      - key: object_name
        value: "{{ item.name.matches.0 }}"
  loop: "{{ protocol_object_objects_group }}"
  export: yes
  register: objects

- name: Generate group-object JSON data structure - 
  json_template:
    template:        
      - key: group_object_name
        value: "{{ item.name.matches.0 }}"
  loop: "{{ protocol_object_group_objects_group }}"
  export: yes
  register: group_objects