---

- name: Import Network Parser role
  include_role:
    name: ansible-network.network-engine

- name: IOS - SNMP CSV reporting task
  include_tasks: ./ios-report.yml
  when: ansible_network_os == "ios"

- name: IOS - SNMP YAML creation task
  include_tasks: ./ios-yaml.yml
  when: ansible_network_os == "ios"
  
#- name: IOS - SNMP configuration task
#  include_tasks: ./ios-config.yml
#  when: ansible_network_os == "ios"

- name: IOS-XR - SNMP CSV reporting task
  include_tasks: ./iosxr-report.yml
  when: ansible_network_os == "iosxr"  

- name: IOS-XR - SNMP YAML creation task
  include_tasks: ./iosxr-yaml.yml
  when: ansible_network_os == "iosxr"

#- name: IOS-XR - SNMP configuration task
#  include_tasks: ./iosxr-config.yml
#  when: ansible_network_os == "iosxr"

- name: NX-OS - SNMP CSV reporting task
  include_tasks: ./nxos-report.yml
  when: ansible_network_os == "nxos"  

- name: NX-OS - SNMP YAML creation task
  include_tasks: ./nxos-yaml.yml
  when: ansible_network_os == "nxos"

#- name: NX-OS - SNMP configuration task
#  include_tasks: ./nxos-config.yml
#  when: ansible_network_os == "nxos"

- name: ASA-SINGLE - SNMP CSV reporting task
  include_tasks: ./asa-single-report.yml
  when: ansible_network_os == "asa" and context_mode == "single"

- name: ASA-SINGLE - SNMP YAML creation task
  include_tasks: ./asa-single-yaml.yml
  when: ansible_network_os == "asa" and context_mode == "single"

#- name: ASA-SINGLE - SNMP configuration task
#  include_tasks: ./asa-single-config.yml
#  when: ansible_network_os == "asa" and context_mode == "single" 

- name: ASA-MULTIPLE - SNMP CSV reporting task
  include_tasks: ./asa-multiple-report.yml
  when: ansible_network_os == "asa" and context_mode == "multiple"

- name: ASA-MULTIPLE - SNMP YAML creation task
  include_tasks: ./asa-multiple-yaml.yml
  when: ansible_network_os == "asa" and context_mode == "multiple"

#- name: ASA-MULTIPLE - SNMP configuration task
#  include_tasks: ./asa-multiple-config.yml
#  when: ansible_network_os == "asa" and context_mode == "multiple" 
